name: Typescript - validate code (eslint)
on: [pull_request]

permissions:
  contents: read
jobs:
  ts-code-validation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Merge branches
        uses: ./.github/actions/merge-branches
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: run npm install
        run: npm install
      - name: typescript code validation with eslint
        run: npm run lint
